import { Product, CATALOG } from '../catalog/products';

export interface ComparisonAttribute {
  key: string;
  values: Record<string, string>;
  winner?: string;
  isHigherBetter: boolean;
}

export interface ComparisonResult {
  products: Product[];
  attributes: ComparisonAttribute[];
  bestPickId: string;
  bestPickReason: string;
  confidenceScore: number;
  userQueryContext?: string;
}

export function compareProducts(productIds: string[], userQuery?: string): ComparisonResult {
  const products = CATALOG.filter(p => productIds.includes(p.id));
  if (products.length === 0) {
    throw new Error("No products found for comparison.");
  }

  // Determine category based on the first product (assuming comparing same category)
  const category = products[0].category;

  const attributes: ComparisonAttribute[] = [
    { key: 'Price', values: {}, isHigherBetter: false },
    { key: 'Rating', values: {}, isHigherBetter: true },
    { key: 'Delivery ETA', values: {}, isHigherBetter: false }
  ];

  // Add category specific attributes
  if (category === 'Electronics Accessories') {
    attributes.push({ key: 'Battery', values: {}, isHigherBetter: true });
    attributes.push({ key: 'Driver Size', values: {}, isHigherBetter: true });
    attributes.push({ key: 'ANC', values: {}, isHigherBetter: true }); // Simple string check, not fully logic based for winner
  } else if (category === 'Snacks' || category === 'Beverages' || category === 'Dairy') {
    attributes.push({ key: 'Flavor', values: {}, isHigherBetter: true });
    attributes.push({ key: 'Unit', values: {}, isHigherBetter: true });
  }

  const scores: Record<string, number> = {};
  products.forEach(p => scores[p.id] = 0);

  attributes.forEach(attr => {
    let bestValue = attr.isHigherBetter ? -Infinity : Infinity;
    let winnerId: string | undefined;

    products.forEach(p => {
      let rawValue: number | undefined;
      let displayValue = '-';

      if (attr.key === 'Price') {
        rawValue = p.price;
        displayValue = `₹${p.price}`;
      } else if (attr.key === 'Rating') {
        rawValue = p.rating;
        displayValue = `${p.rating} ⭐`;
      } else if (attr.key === 'Delivery ETA') {
        rawValue = p.eta_minutes;
        displayValue = `~${p.eta_minutes} min`;
      } else if (p.attributes[attr.key]) {
        displayValue = p.attributes[attr.key];
        // naive extraction of numbers for comparison
        const numMatch = displayValue.match(/(\d+(\.\d+)?)/);
        if (numMatch) rawValue = parseFloat(numMatch[1]);
      } else if (attr.key === 'Unit') {
        displayValue = p.unit;
      }

      attr.values[p.id] = displayValue;

      if (rawValue !== undefined) {
        if (attr.isHigherBetter && rawValue > bestValue) {
          bestValue = rawValue;
          winnerId = p.id;
        } else if (!attr.isHigherBetter && rawValue < bestValue) {
          bestValue = rawValue;
          winnerId = p.id;
        }
      }
    });

    if (winnerId) {
      attr.winner = winnerId;
      // Adjust weights slightly based on query
      let weight = 10;
      const lowerQuery = userQuery?.toLowerCase() || '';
      if (attr.key === 'Price' && (lowerQuery.includes('cheap') || lowerQuery.includes('budget'))) weight += 10;
      if (attr.key === 'Rating' && (lowerQuery.includes('best') || lowerQuery.includes('rated'))) weight += 10;
      if (attr.key === 'Delivery ETA' && (lowerQuery.includes('fast') || lowerQuery.includes('jaldi'))) weight += 10;
      if (attr.key === 'Driver Size' && lowerQuery.includes('bass')) weight += 15;

      scores[winnerId] += weight;
    }
  });

  // Find best pick
  let bestPickId = products[0].id;
  let maxScore = -Infinity;
  for (const [id, score] of Object.entries(scores)) {
    if (score > maxScore) {
      maxScore = score;
      bestPickId = id;
    }
  }

  const bestProduct = products.find(p => p.id === bestPickId);
  const bestPickReason = `Best overall choice based on your preferences. Strong performance in key metrics compared to alternatives.`;

  return {
    products,
    attributes,
    bestPickId,
    bestPickReason,
    confidenceScore: Math.min(100, 70 + maxScore),
    userQueryContext: userQuery
  };
}

// Production extension:
// In production, comparison attributes would be auto-populated from a dynamic product attribute graph.
// The bestPickReason would be generated by a Bedrock call with the comparison matrix injected as context.
